/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import code.Koneksi;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.sql.*;

/**
 *
 * @author M13
 */
public class Rental extends javax.swing.JFrame {
    private int kode;
    private String username;
    /**
     * Creates new form Rental
     */
    public Rental() {
        initComponents();
        setLocationRelativeTo(null);
    }
    public void setKode(int kode){
        this.kode = kode;
    }
    public void setUsername(String username){
        this.username = username;
        userLabel.setText(username);
    }
    public void checkPrivilege(){
        if (kode == 0){
            jTabbedPane1.setEnabledAt(3, false);
            homeTextArea.append("Note: Fitur manajemen administrasi pegawai hanya tersedia bagi administrator");
        } else {
            homeTextArea.append("Anda memiliki akses administrator");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        homePanel = new javax.swing.JPanel();
        keluarButton = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        homeTextArea = new javax.swing.JTextArea();
        dataPelangganPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pelangganTable = new javax.swing.JTable();
        pelangganPanel = new javax.swing.JPanel();
        hapusPelangganButton = new javax.swing.JButton();
        namaPelangganLabel = new javax.swing.JLabel();
        namaPelangganField = new javax.swing.JTextField();
        alamatLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatTextArea = new javax.swing.JTextArea();
        cpLabel = new javax.swing.JLabel();
        cpField = new javax.swing.JTextField();
        simpanPelangganButton = new javax.swing.JButton();
        baruPelangganButton = new javax.swing.JButton();
        batalPelangganButton = new javax.swing.JButton();
        pilihPelangganButton = new javax.swing.JButton();
        pilihPelangganField = new javax.swing.JTextField();
        cariPelangganButton = new javax.swing.JButton();
        cariPelangganField = new javax.swing.JTextField();
        dataKendaraanPanel = new javax.swing.JPanel();
        kendaraanPanel = new javax.swing.JPanel();
        hapusKendaraanButton = new javax.swing.JButton();
        jenisLabel = new javax.swing.JLabel();
        jenisField = new javax.swing.JTextField();
        hargaLabel = new javax.swing.JLabel();
        stokLabel = new javax.swing.JLabel();
        stokField = new javax.swing.JTextField();
        simpanKendaraanButton = new javax.swing.JButton();
        baruKendaraanButton = new javax.swing.JButton();
        batalKendaraanButton = new javax.swing.JButton();
        hargaField = new javax.swing.JTextField();
        pilihKendaraanButton = new javax.swing.JButton();
        pilihKendaraanField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        kendaraanTable = new javax.swing.JTable();
        dataPegawaiPanel = new javax.swing.JPanel();
        pegawaiPanel = new javax.swing.JPanel();
        hapusPegawaiButton = new javax.swing.JButton();
        usernamePegawaiLabel = new javax.swing.JLabel();
        usernamePegawaiField = new javax.swing.JTextField();
        passwordPegawaiLabel = new javax.swing.JLabel();
        passwordPegawaiField = new javax.swing.JTextField();
        simpanPegawaiButton = new javax.swing.JButton();
        baruPegawaiButton = new javax.swing.JButton();
        batalPegawaiButton = new javax.swing.JButton();
        pilihPegawaiButton = new javax.swing.JButton();
        pilihPegawaiField = new javax.swing.JTextField();
        adminCheckBox = new javax.swing.JCheckBox();
        cariPegawaiButton = new javax.swing.JButton();
        cariPegawaiField = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        pegawaiTable = new javax.swing.JTable();
        peminjamanPanel = new javax.swing.JPanel();
        peminjamanPanel1 = new javax.swing.JPanel();
        idPelangganPeminjamanLabel = new javax.swing.JLabel();
        jenisPeminjamanLabel = new javax.swing.JLabel();
        jenisPeminjamanComboBox = new javax.swing.JComboBox<>();
        tanggalPesanLabel = new javax.swing.JLabel();
        tanggalPesanPeminjamanField = new javax.swing.JFormattedTextField();
        lamaPeminjamanLabel = new javax.swing.JLabel();
        lamaPeminjamanField = new javax.swing.JTextField();
        prosesButton = new javax.swing.JButton();
        lamaHariPeminjamanLabel = new javax.swing.JLabel();
        pegawaiPeminjamanLabel = new javax.swing.JLabel();
        pegawaiPeminjamanComboBox = new javax.swing.JComboBox<>();
        pelangganPeminjamanComboBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        biayaPeminjamanLabel = new javax.swing.JLabel();
        biayaPeminjamanField = new javax.swing.JTextField();
        biayaPerHariPeminjamanLabel = new javax.swing.JLabel();
        totalPeminjamanLabel = new javax.swing.JLabel();
        totalPeminjamanField = new javax.swing.JTextField();
        tanggalKembaliPeminjamanField = new javax.swing.JFormattedTextField();
        tanggalPesanLabel1 = new javax.swing.JLabel();
        simpanPeminjamanButton = new javax.swing.JButton();
        batalPeminjamanButton = new javax.swing.JButton();
        transaksiPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        transaksiTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setToolTipText("");

        homePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        keluarButton.setText("Keluar");
        keluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarButtonActionPerformed(evt);
            }
        });

        welcomeLabel.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        welcomeLabel.setText("Selamat Datang");

        userLabel.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N

        homeTextArea.setEditable(false);
        homeTextArea.setColumns(20);
        homeTextArea.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        homeTextArea.setRows(5);
        homeTextArea.setText("Selamat Datang di Aplikasi Manajemen Rental Kendaraan V2.2\nFitur-fitur yang tersedia:\n- Manajemen data pelanggan\n- Manajemen data kendaraan\n- Manajemen administrasi pegawai\n- Pendataan riwayat transaksi\n\n");
        jScrollPane5.setViewportView(homeTextArea);

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(keluarButton))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userLabel)
                        .addGap(0, 521, Short.MAX_VALUE)))
                .addContainerGap())
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLabel)
                    .addComponent(userLabel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(keluarButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Home", homePanel);

        dataPelangganPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        dataPelangganPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                dataPelangganPanelComponentShown(evt);
            }
        });

        pelangganTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Alamat", "Contact Person"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pelangganTable.setToolTipText("");
        jScrollPane1.setViewportView(pelangganTable);
        if (pelangganTable.getColumnModel().getColumnCount() > 0) {
            pelangganTable.getColumnModel().getColumn(0).setPreferredWidth(15);
        }

        pelangganPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pelangganPanel.setPreferredSize(new java.awt.Dimension(354, 248));

        hapusPelangganButton.setText("Hapus");
        hapusPelangganButton.setEnabled(false);
        hapusPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPelangganButtonActionPerformed(evt);
            }
        });

        namaPelangganLabel.setText("Nama:");

        namaPelangganField.setEnabled(false);

        alamatLabel.setText("Alamat:");

        alamatTextArea.setColumns(20);
        alamatTextArea.setRows(5);
        alamatTextArea.setEnabled(false);
        jScrollPane2.setViewportView(alamatTextArea);

        cpLabel.setText("Contact Person:");

        cpField.setEnabled(false);

        simpanPelangganButton.setText("Simpan");
        simpanPelangganButton.setEnabled(false);
        simpanPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPelangganButtonActionPerformed(evt);
            }
        });

        baruPelangganButton.setText("Baru");
        baruPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baruPelangganButtonActionPerformed(evt);
            }
        });

        batalPelangganButton.setText("Batal");
        batalPelangganButton.setEnabled(false);
        batalPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalPelangganButtonActionPerformed(evt);
            }
        });

        pilihPelangganButton.setText("Pilih (ID)");
        pilihPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihPelangganButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pelangganPanelLayout = new javax.swing.GroupLayout(pelangganPanel);
        pelangganPanel.setLayout(pelangganPanelLayout);
        pelangganPanelLayout.setHorizontalGroup(
            pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pelangganPanelLayout.createSequentialGroup()
                        .addComponent(baruPelangganButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simpanPelangganButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapusPelangganButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(batalPelangganButton))
                    .addGroup(pelangganPanelLayout.createSequentialGroup()
                        .addGroup(pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pilihPelangganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaPelangganLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alamatLabel)
                            .addComponent(cpLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaPelangganField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pilihPelangganField)
                            .addComponent(cpField))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pelangganPanelLayout.setVerticalGroup(
            pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihPelangganButton)
                    .addComponent(pilihPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPelangganLabel)
                    .addComponent(namaPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamatLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpLabel)
                    .addComponent(cpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanPelangganButton)
                    .addComponent(baruPelangganButton)
                    .addComponent(batalPelangganButton)
                    .addComponent(hapusPelangganButton))
                .addContainerGap())
        );

        cariPelangganButton.setText("Cari (Nama)");
        cariPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariPelangganButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataPelangganPanelLayout = new javax.swing.GroupLayout(dataPelangganPanel);
        dataPelangganPanel.setLayout(dataPelangganPanelLayout);
        dataPelangganPanelLayout.setHorizontalGroup(
            dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pelangganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                    .addGroup(dataPelangganPanelLayout.createSequentialGroup()
                        .addComponent(cariPelangganButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cariPelangganField)))
                .addContainerGap())
        );
        dataPelangganPanelLayout.setVerticalGroup(
            dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pelangganPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dataPelangganPanelLayout.createSequentialGroup()
                        .addGroup(dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cariPelangganButton)
                            .addComponent(cariPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data Pelanggan", dataPelangganPanel);

        dataKendaraanPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        dataKendaraanPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                dataKendaraanPanelComponentShown(evt);
            }
        });

        kendaraanPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        kendaraanPanel.setPreferredSize(new java.awt.Dimension(354, 248));

        hapusKendaraanButton.setText("Hapus");
        hapusKendaraanButton.setEnabled(false);
        hapusKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusKendaraanButtonActionPerformed(evt);
            }
        });

        jenisLabel.setText("Jenis:");

        jenisField.setEnabled(false);

        hargaLabel.setText("Harga:");

        stokLabel.setText("Stok:");

        stokField.setEnabled(false);

        simpanKendaraanButton.setText("Simpan");
        simpanKendaraanButton.setEnabled(false);
        simpanKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanKendaraanButtonActionPerformed(evt);
            }
        });

        baruKendaraanButton.setText("Baru");
        baruKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baruKendaraanButtonActionPerformed(evt);
            }
        });

        batalKendaraanButton.setText("Batal");
        batalKendaraanButton.setEnabled(false);
        batalKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalKendaraanButtonActionPerformed(evt);
            }
        });

        hargaField.setEnabled(false);

        pilihKendaraanButton.setText("Pilih (ID)");
        pilihKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihKendaraanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kendaraanPanelLayout = new javax.swing.GroupLayout(kendaraanPanel);
        kendaraanPanel.setLayout(kendaraanPanelLayout);
        kendaraanPanelLayout.setHorizontalGroup(
            kendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kendaraanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kendaraanPanelLayout.createSequentialGroup()
                        .addComponent(baruKendaraanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simpanKendaraanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapusKendaraanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(batalKendaraanButton))
                    .addGroup(kendaraanPanelLayout.createSequentialGroup()
                        .addGroup(kendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hargaLabel)
                            .addComponent(jenisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stokLabel))
                        .addGap(69, 69, 69)
                        .addGroup(kendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hargaField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jenisField)
                            .addComponent(stokField)))
                    .addGroup(kendaraanPanelLayout.createSequentialGroup()
                        .addComponent(pilihKendaraanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pilihKendaraanField)))
                .addContainerGap())
        );
        kendaraanPanelLayout.setVerticalGroup(
            kendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kendaraanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihKendaraanButton)
                    .addComponent(pilihKendaraanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisLabel)
                    .addComponent(jenisField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaLabel)
                    .addComponent(hargaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stokLabel)
                    .addComponent(stokField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(kendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanKendaraanButton)
                    .addComponent(baruKendaraanButton)
                    .addComponent(batalKendaraanButton)
                    .addComponent(hapusKendaraanButton))
                .addContainerGap())
        );

        kendaraanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Jenis", "Sewa", "Stok"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(kendaraanTable);

        javax.swing.GroupLayout dataKendaraanPanelLayout = new javax.swing.GroupLayout(dataKendaraanPanel);
        dataKendaraanPanel.setLayout(dataKendaraanPanelLayout);
        dataKendaraanPanelLayout.setHorizontalGroup(
            dataKendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataKendaraanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kendaraanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );
        dataKendaraanPanelLayout.setVerticalGroup(
            dataKendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataKendaraanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataKendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(kendaraanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data Kendaraan", dataKendaraanPanel);

        dataPegawaiPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        dataPegawaiPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                dataPegawaiPanelComponentShown(evt);
            }
        });

        pegawaiPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pegawaiPanel.setPreferredSize(new java.awt.Dimension(354, 248));

        hapusPegawaiButton.setText("Hapus");
        hapusPegawaiButton.setEnabled(false);
        hapusPegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPegawaiButtonActionPerformed(evt);
            }
        });

        usernamePegawaiLabel.setText("Username:");

        usernamePegawaiField.setEnabled(false);

        passwordPegawaiLabel.setText("Password:");

        passwordPegawaiField.setEnabled(false);

        simpanPegawaiButton.setText("Simpan");
        simpanPegawaiButton.setEnabled(false);
        simpanPegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPegawaiButtonActionPerformed(evt);
            }
        });

        baruPegawaiButton.setText("Baru");
        baruPegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baruPegawaiButtonActionPerformed(evt);
            }
        });

        batalPegawaiButton.setText("Batal");
        batalPegawaiButton.setEnabled(false);
        batalPegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalPegawaiButtonActionPerformed(evt);
            }
        });

        pilihPegawaiButton.setText("Pilih (ID)");
        pilihPegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihPegawaiButtonActionPerformed(evt);
            }
        });

        adminCheckBox.setText("Admin");
        adminCheckBox.setEnabled(false);

        javax.swing.GroupLayout pegawaiPanelLayout = new javax.swing.GroupLayout(pegawaiPanel);
        pegawaiPanel.setLayout(pegawaiPanelLayout);
        pegawaiPanelLayout.setHorizontalGroup(
            pegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pegawaiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pegawaiPanelLayout.createSequentialGroup()
                        .addComponent(baruPegawaiButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simpanPegawaiButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapusPegawaiButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(batalPegawaiButton))
                    .addGroup(pegawaiPanelLayout.createSequentialGroup()
                        .addGroup(pegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pilihPegawaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernamePegawaiLabel)
                            .addComponent(passwordPegawaiLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pegawaiPanelLayout.createSequentialGroup()
                                .addComponent(adminCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(passwordPegawaiField)
                            .addComponent(usernamePegawaiField)
                            .addComponent(pilihPegawaiField))))
                .addContainerGap())
        );
        pegawaiPanelLayout.setVerticalGroup(
            pegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pegawaiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihPegawaiButton)
                    .addComponent(pilihPegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernamePegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernamePegawaiLabel))
                .addGap(18, 18, 18)
                .addGroup(pegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordPegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordPegawaiLabel))
                .addGap(18, 18, 18)
                .addComponent(adminCheckBox)
                .addGap(72, 72, 72)
                .addGroup(pegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanPegawaiButton)
                    .addComponent(baruPegawaiButton)
                    .addComponent(batalPegawaiButton)
                    .addComponent(hapusPegawaiButton))
                .addContainerGap())
        );

        cariPegawaiButton.setText("Cari (User)");
        cariPegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariPegawaiButtonActionPerformed(evt);
            }
        });

        pegawaiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Username", "Password", "Privilege"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(pegawaiTable);
        if (pegawaiTable.getColumnModel().getColumnCount() > 0) {
            pegawaiTable.getColumnModel().getColumn(0).setPreferredWidth(15);
        }

        javax.swing.GroupLayout dataPegawaiPanelLayout = new javax.swing.GroupLayout(dataPegawaiPanel);
        dataPegawaiPanel.setLayout(dataPegawaiPanelLayout);
        dataPegawaiPanelLayout.setHorizontalGroup(
            dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPegawaiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pegawaiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataPegawaiPanelLayout.createSequentialGroup()
                        .addComponent(cariPegawaiButton, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cariPegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        dataPegawaiPanelLayout.setVerticalGroup(
            dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPegawaiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dataPegawaiPanelLayout.createSequentialGroup()
                        .addGroup(dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cariPegawaiButton)
                            .addComponent(cariPegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(pegawaiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data Pegawai", dataPegawaiPanel);

        peminjamanPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        peminjamanPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                peminjamanPanelComponentShown(evt);
            }
        });

        peminjamanPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        peminjamanPanel1.setPreferredSize(new java.awt.Dimension(354, 248));

        idPelangganPeminjamanLabel.setText("Pelanggan:");

        jenisPeminjamanLabel.setText("Jenis:");

        tanggalPesanLabel.setText("Tanggal Pesan:");

        tanggalPesanPeminjamanField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        lamaPeminjamanLabel.setText("Lama Pinjam:");

        prosesButton.setText("Proses");
        prosesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesButtonActionPerformed(evt);
            }
        });

        lamaHariPeminjamanLabel.setText("hari");

        pegawaiPeminjamanLabel.setText("Pegawai:");

        pelangganPeminjamanComboBox.setPreferredSize(new java.awt.Dimension(104, 22));

        javax.swing.GroupLayout peminjamanPanel1Layout = new javax.swing.GroupLayout(peminjamanPanel1);
        peminjamanPanel1.setLayout(peminjamanPanel1Layout);
        peminjamanPanel1Layout.setHorizontalGroup(
            peminjamanPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peminjamanPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(peminjamanPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prosesButton)
                    .addGroup(peminjamanPanel1Layout.createSequentialGroup()
                        .addGroup(peminjamanPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(peminjamanPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tanggalPesanLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                .addComponent(lamaPeminjamanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(pegawaiPeminjamanLabel)
                            .addGroup(peminjamanPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jenisPeminjamanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idPelangganPeminjamanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(13, 13, 13)
                        .addGroup(peminjamanPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jenisPeminjamanComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lamaPeminjamanField)
                            .addComponent(tanggalPesanPeminjamanField)
                            .addComponent(pegawaiPeminjamanComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pelangganPeminjamanComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lamaHariPeminjamanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96))
        );
        peminjamanPanel1Layout.setVerticalGroup(
            peminjamanPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, peminjamanPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(peminjamanPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idPelangganPeminjamanLabel)
                    .addComponent(pelangganPeminjamanComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(peminjamanPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisPeminjamanLabel)
                    .addComponent(jenisPeminjamanComboBox))
                .addGap(15, 15, 15)
                .addGroup(peminjamanPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pegawaiPeminjamanLabel)
                    .addComponent(pegawaiPeminjamanComboBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(peminjamanPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggalPesanLabel)
                    .addComponent(tanggalPesanPeminjamanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(peminjamanPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lamaPeminjamanLabel)
                    .addComponent(lamaPeminjamanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lamaHariPeminjamanLabel))
                .addGap(55, 55, 55)
                .addComponent(prosesButton)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        biayaPeminjamanLabel.setText("Biaya Sewa:");

        biayaPeminjamanField.setEditable(false);

        biayaPerHariPeminjamanLabel.setText("per hari");

        totalPeminjamanLabel.setText("Total Sewa:");

        totalPeminjamanField.setEditable(false);

        tanggalKembaliPeminjamanField.setEditable(false);
        tanggalKembaliPeminjamanField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        tanggalPesanLabel1.setText("Tanggal Kembali:");

        simpanPeminjamanButton.setText("Simpan");
        simpanPeminjamanButton.setEnabled(false);
        simpanPeminjamanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPeminjamanButtonActionPerformed(evt);
            }
        });

        batalPeminjamanButton.setText("Batal");
        batalPeminjamanButton.setEnabled(false);
        batalPeminjamanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalPeminjamanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(simpanPeminjamanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(batalPeminjamanButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tanggalPesanLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(biayaPeminjamanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalPeminjamanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tanggalKembaliPeminjamanField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(biayaPeminjamanField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalPeminjamanField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(biayaPerHariPeminjamanLabel)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(biayaPeminjamanLabel)
                    .addComponent(biayaPeminjamanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biayaPerHariPeminjamanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPeminjamanLabel)
                    .addComponent(totalPeminjamanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggalPesanLabel1)
                    .addComponent(tanggalKembaliPeminjamanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanPeminjamanButton)
                    .addComponent(batalPeminjamanButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout peminjamanPanelLayout = new javax.swing.GroupLayout(peminjamanPanel);
        peminjamanPanel.setLayout(peminjamanPanelLayout);
        peminjamanPanelLayout.setHorizontalGroup(
            peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peminjamanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(peminjamanPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        peminjamanPanelLayout.setVerticalGroup(
            peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peminjamanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(peminjamanPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Peminjaman", peminjamanPanel);

        transaksiPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        transaksiPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                transaksiPanelComponentShown(evt);
            }
        });

        transaksiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Pelanggan", "Kendaraan", "Pegawai", "Tanggal Pesan", "Tanggal Kembali", "Lama Pinjam", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(transaksiTable);
        if (transaksiTable.getColumnModel().getColumnCount() > 0) {
            transaksiTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        javax.swing.GroupLayout transaksiPanelLayout = new javax.swing.GroupLayout(transaksiPanel);
        transaksiPanel.setLayout(transaksiPanelLayout);
        transaksiPanelLayout.setHorizontalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
                .addContainerGap())
        );
        transaksiPanelLayout.setVerticalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Transaksi", transaksiPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void dataPelangganPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_dataPelangganPanelComponentShown
        showPelanggan();
    }//GEN-LAST:event_dataPelangganPanelComponentShown

    private void hapusPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPelangganButtonActionPerformed
        String query = pilihPelangganField.getText();
        try {
            Koneksi conn = new Koneksi();
            conn.query("DELETE FROM pelanggan WHERE pelanggan_id = '" + query + "'");
        } catch (Exception e){}
        namaPelangganField.setText("");
        namaPelangganField.setEnabled(false);
        alamatTextArea.setText("");
        alamatTextArea.setEnabled(false);
        cpField.setText("");
        cpField.setEnabled(false);
        simpanPelangganButton.setEnabled(false);
        hapusPelangganButton.setEnabled(false);
        batalPelangganButton.setEnabled(false);
        baruPelangganButton.setEnabled(true);
        pilihPelangganButton.setEnabled(true);
        pilihPelangganField.setText("");
        pilihPelangganField.setEnabled(true);
        refreshPelanggan();
        showPelanggan();
    }//GEN-LAST:event_hapusPelangganButtonActionPerformed

    private void cariPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariPelangganButtonActionPerformed
        refreshPelanggan();
        String query = cariPelangganField.getText();
        int baris = 0;
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM pelanggan WHERE nama LIKE '%" + query + "%'");

            while (rs.next()){
                pelangganTable.setValueAt(rs.getString("pelanggan_id"), baris, 0);
                pelangganTable.setValueAt(rs.getString("nama"), baris, 1);
                pelangganTable.setValueAt(rs.getString("alamat"), baris, 2);
                pelangganTable.setValueAt(rs.getString("cp"), baris, 3);
                baris++;
            }
            rs.close();
        } catch (SQLException e){}
    }//GEN-LAST:event_cariPelangganButtonActionPerformed

    private void simpanPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPelangganButtonActionPerformed
        try {
            Koneksi conn = new Koneksi();
            if (pilihPelangganField.getText().equals("")){
                conn.query("INSERT INTO pelanggan (nama, alamat, cp) VALUES ('"+namaPelangganField.getText()+"','"+alamatTextArea.getText()+"','"+cpField.getText()+"')");
            } else{
                conn.query("UPDATE pelanggan SET nama='"+namaPelangganField.getText()+"', alamat='"+alamatTextArea.getText()+"', cp='"+cpField.getText()+"' WHERE pelanggan_id='"+pilihPelangganField.getText()+"'");
            }
        } catch (Exception e){}
        namaPelangganField.setText("");
        namaPelangganField.setEnabled(false);
        alamatTextArea.setText("");
        alamatTextArea.setEnabled(false);
        cpField.setText("");
        cpField.setEnabled(false);
        simpanPelangganButton.setEnabled(false);
        hapusPelangganButton.setEnabled(false);
        batalPelangganButton.setEnabled(false);
        baruPelangganButton.setEnabled(true);
        pilihPelangganButton.setEnabled(true);
        pilihPelangganField.setText("");
        pilihPelangganField.setEnabled(true);
        refreshPelanggan();
        showPelanggan();
    }//GEN-LAST:event_simpanPelangganButtonActionPerformed

    private void baruPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baruPelangganButtonActionPerformed
        namaPelangganField.setEnabled(true);
        alamatTextArea.setEnabled(true);
        cpField.setEnabled(true);
        simpanPelangganButton.setEnabled(true);
        batalPelangganButton.setEnabled(true);
        baruPelangganButton.setEnabled(false);
        pilihPelangganButton.setEnabled(false);
        pilihPelangganField.setText("");
        pilihPelangganField.setEnabled(false);
    }//GEN-LAST:event_baruPelangganButtonActionPerformed

    private void batalPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalPelangganButtonActionPerformed
        namaPelangganField.setText("");
        namaPelangganField.setEnabled(false);
        alamatTextArea.setText("");
        alamatTextArea.setEnabled(false);
        cpField.setText("");
        cpField.setEnabled(false);
        simpanPelangganButton.setEnabled(false);
        hapusPelangganButton.setEnabled(false);
        batalPelangganButton.setEnabled(false);
        baruPelangganButton.setEnabled(true);
        pilihPelangganButton.setEnabled(true);
        pilihPelangganField.setEnabled(true);
    }//GEN-LAST:event_batalPelangganButtonActionPerformed

    private void pilihPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihPelangganButtonActionPerformed
        if (cekPelanggan(pilihPelangganField.getText())){
            String id = pilihPelangganField.getText();
            ResultSet rs = null;
            try{
                Koneksi conn = new Koneksi();
                rs = conn.getData("SELECT * FROM pelanggan WHERE pelanggan_id='"+id+"'");
                
                while (rs.next()){
                    namaPelangganField.setText(rs.getString("nama"));
                    alamatTextArea.setText(rs.getString("alamat"));
                    cpField.setText(rs.getString("cp"));
                }
                rs.close();
            } catch (SQLException e) {}
            namaPelangganField.setEnabled(true);
            alamatTextArea.setEnabled(true);
            cpField.setEnabled(true);
            simpanPelangganButton.setEnabled(true);
            hapusPelangganButton.setEnabled(true);
            batalPelangganButton.setEnabled(true);
            baruPelangganButton.setEnabled(false);
            pilihPelangganButton.setEnabled(false);
            pilihPelangganField.setEnabled(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "ID tidak ditemukan");
        }
    }//GEN-LAST:event_pilihPelangganButtonActionPerformed

    private void keluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarButtonActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_keluarButtonActionPerformed

    private void hapusKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusKendaraanButtonActionPerformed
        String query = pilihKendaraanField.getText();
        try {
            Koneksi conn = new Koneksi();
            conn.query("DELETE FROM kendaraan WHERE kendaraan_id = '" + query + "'");
        } catch (Exception e){}
        jenisField.setText("");
        jenisField.setEnabled(false);
        hargaField.setText("");
        hargaField.setEnabled(false);
        stokField.setText("");
        stokField.setEnabled(false);
        simpanKendaraanButton.setEnabled(false);
        hapusKendaraanButton.setEnabled(false);
        batalKendaraanButton.setEnabled(false);
        baruKendaraanButton.setEnabled(true);
        pilihKendaraanButton.setEnabled(true);
        pilihKendaraanField.setText("");
        pilihKendaraanField.setEnabled(true);
        refreshKendaraan();
        showKendaraan();
    }//GEN-LAST:event_hapusKendaraanButtonActionPerformed

    private void simpanKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanKendaraanButtonActionPerformed
        try {
            Koneksi conn = new Koneksi();
            if (pilihKendaraanField.getText().equals("")){
                conn.query("INSERT INTO kendaraan (jenis, harga, stok) VALUES ('"+jenisField.getText()+"','"+hargaField.getText()+"','"+stokField.getText()+"')");
            } else{
                conn.query("UPDATE kendaraan SET jenis='"+jenisField.getText()+"', harga='"+hargaField.getText()+"', stok='"+stokField.getText()+"' WHERE kendaraan_id='"+pilihKendaraanField.getText()+"'");
            }
        } catch (Exception e){}
        jenisField.setText("");
        jenisField.setEnabled(false);
        hargaField.setText("");
        hargaField.setEnabled(false);
        stokField.setText("");
        stokField.setEnabled(false);
        simpanKendaraanButton.setEnabled(false);
        hapusKendaraanButton.setEnabled(false);
        batalKendaraanButton.setEnabled(false);
        baruKendaraanButton.setEnabled(true);
        pilihKendaraanButton.setEnabled(true);
        pilihKendaraanField.setText("");
        pilihKendaraanField.setEnabled(true);
        refreshKendaraan();
        showKendaraan();
    }//GEN-LAST:event_simpanKendaraanButtonActionPerformed

    private void baruKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baruKendaraanButtonActionPerformed
        jenisField.setEnabled(true);
        hargaField.setEnabled(true);
        stokField.setEnabled(true);
        simpanKendaraanButton.setEnabled(true);
        batalKendaraanButton.setEnabled(true);
        baruKendaraanButton.setEnabled(false);
        pilihKendaraanButton.setEnabled(false);
        pilihKendaraanField.setText("");
        pilihKendaraanField.setEnabled(false);
    }//GEN-LAST:event_baruKendaraanButtonActionPerformed

    private void batalKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalKendaraanButtonActionPerformed
        jenisField.setText("");
        jenisField.setEnabled(false);
        hargaField.setText("");
        hargaField.setEnabled(false);
        stokField.setText("");
        stokField.setEnabled(false);
        simpanKendaraanButton.setEnabled(false);
        hapusKendaraanButton.setEnabled(false);
        batalKendaraanButton.setEnabled(false);
        baruKendaraanButton.setEnabled(true);
        pilihKendaraanButton.setEnabled(true);
        pilihKendaraanField.setEnabled(true);
    }//GEN-LAST:event_batalKendaraanButtonActionPerformed

    private void pilihKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihKendaraanButtonActionPerformed
        if (cekKendaraan(pilihKendaraanField.getText())){
            String id = pilihKendaraanField.getText();
            ResultSet rs = null;
            try{
                Koneksi conn = new Koneksi();
                rs = conn.getData("SELECT * FROM kendaraan WHERE kendaraan_id='"+id+"'");
                
                while (rs.next()){
                    jenisField.setText(rs.getString("jenis"));
                    hargaField.setText(rs.getString("harga"));
                    stokField.setText(rs.getString("stok"));
                    rs.close();
                }
            } catch (SQLException e) {}
            jenisField.setEnabled(true);
            hargaField.setEnabled(true);
            stokField.setEnabled(true);
            simpanKendaraanButton.setEnabled(true);
            hapusKendaraanButton.setEnabled(true);
            batalKendaraanButton.setEnabled(true);
            baruKendaraanButton.setEnabled(false);
            pilihKendaraanButton.setEnabled(false);
            pilihKendaraanField.setEnabled(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "ID tidak ditemukan");
        }
    }//GEN-LAST:event_pilihKendaraanButtonActionPerformed

    private void peminjamanPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_peminjamanPanelComponentShown
        pelangganPeminjamanComboBox.removeAllItems();
        pelangganPeminjamanComboBox.addItem("");
        jenisPeminjamanComboBox.removeAllItems();
        jenisPeminjamanComboBox.addItem("");
        pegawaiPeminjamanComboBox.removeAllItems();
        pegawaiPeminjamanComboBox.addItem("");
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM pelanggan");
            while(rs.next()) {
                pelangganPeminjamanComboBox.addItem(rs.getString("nama"));
            }
            
            rs = conn.getData("SELECT * FROM kendaraan");
            while(rs.next()) {
                jenisPeminjamanComboBox.addItem(rs.getString("jenis"));
            }
            
            rs = conn.getData("SELECT * FROM pegawai");
            while(rs.next()) {
                pegawaiPeminjamanComboBox.addItem(rs.getString("username"));
            }
            rs.close();
        } catch(SQLException e) {}
    }//GEN-LAST:event_peminjamanPanelComponentShown

    private void prosesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesButtonActionPerformed
        try {
            int sewa = 0;
            try {
                Koneksi conn = new Koneksi();
                ResultSet rs = null;
                rs = conn.getData("SELECT * FROM kendaraan WHERE jenis='"+jenisPeminjamanComboBox.getSelectedItem()+"'");
                rs.next();
                biayaPeminjamanField.setText(rs.getString("harga"));            
                sewa = Integer.parseInt(rs.getString("harga"));
                rs.close();
            } catch (SQLException e) {}

            int lama = Integer.parseInt(lamaPeminjamanField.getText());
            totalPeminjamanField.setText(Integer.toString(lama*sewa));

            SimpleDateFormat formatTanggal = new SimpleDateFormat("dd/MM/yyyy");
            Calendar cal = Calendar.getInstance();
            try {
                cal.setTime(formatTanggal.parse(tanggalPesanPeminjamanField.getText()));
                cal.add(Calendar.DATE, lama);
                String output = formatTanggal.format(cal.getTime());
                tanggalKembaliPeminjamanField.setText(output);
            } catch (ParseException e){}
            
            pelangganPeminjamanComboBox.setEnabled(false);
            jenisPeminjamanComboBox.setEnabled(false);
            pegawaiPeminjamanComboBox.setEnabled(false);
            tanggalPesanPeminjamanField.setEnabled(false);
            lamaPeminjamanField.setEnabled(false);
            simpanPeminjamanButton.setEnabled(true);
            batalPeminjamanButton.setEnabled(true);
        } catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, "Kesalahan input");
        }
    }//GEN-LAST:event_prosesButtonActionPerformed

    private void simpanPeminjamanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPeminjamanButtonActionPerformed
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM pelanggan WHERE nama='"+pelangganPeminjamanComboBox.getSelectedItem()+"'");
            rs.next();
            String pelanggan_id = rs.getString("pelanggan_id");
            
            rs = conn.getData("SELECT * FROM kendaraan WHERE jenis='"+jenisPeminjamanComboBox.getSelectedItem()+"'");
            rs.next();
            String kendaraan_id = rs.getString("kendaraan_id");
            
            rs = conn.getData("SELECT * FROM pegawai WHERE username='"+pegawaiPeminjamanComboBox.getSelectedItem()+"'");
            rs.next();
            String pegawai_id = rs.getString("user_id");
            rs.close();
            
            String pesanFormatted = tanggalPesanPeminjamanField.getText();
            String[] pesanSplit = pesanFormatted.split("/");
            pesanFormatted = pesanSplit[2]+"-"+pesanSplit[1]+"-"+pesanSplit[0];
            String kembaliFormatted = tanggalKembaliPeminjamanField.getText();
            String[] kembaliSplit = kembaliFormatted.split("/");
            kembaliFormatted = kembaliSplit[2]+"-"+kembaliSplit[1]+"-"+kembaliSplit[0];
            String query = "INSERT INTO transaksi (pelanggan_id, kendaraan_id, user_id, tanggal_pesan, tanggal_kembali, lama_pinjam, total) "
                    + "VALUES ('"+pelanggan_id+"','"+kendaraan_id+"','"+pegawai_id+"','"+pesanFormatted+"','"+kembaliFormatted+"','"+lamaPeminjamanField.getText()+"','"+totalPeminjamanField.getText()+"')";
            conn.query(query);
            
            bersihPeminjaman();
        } catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_simpanPeminjamanButtonActionPerformed

    private void dataKendaraanPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_dataKendaraanPanelComponentShown
        showKendaraan();
    }//GEN-LAST:event_dataKendaraanPanelComponentShown

    private void transaksiPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_transaksiPanelComponentShown
        showTransaksi();
    }//GEN-LAST:event_transaksiPanelComponentShown

    private void batalPeminjamanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalPeminjamanButtonActionPerformed
        bersihPeminjaman();
    }//GEN-LAST:event_batalPeminjamanButtonActionPerformed

    private void hapusPegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPegawaiButtonActionPerformed
        String query = pilihPegawaiField.getText();
        try {
            Koneksi conn = new Koneksi();
            conn.query("DELETE FROM pegawai WHERE user_id = '" + query + "'");
        } catch (Exception e){}
        bersihPegawai();
        refreshPegawai();
        showPegawai();
    }//GEN-LAST:event_hapusPegawaiButtonActionPerformed

    private void simpanPegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPegawaiButtonActionPerformed
        try {
            Koneksi conn = new Koneksi();
            int kode = 0;
            if (adminCheckBox.isSelected()){
                kode = 1;
            }
            if (pilihPegawaiField.getText().equals("")){
                conn.query("INSERT INTO pegawai (username, password, kode) VALUES ('"+usernamePegawaiField.getText()+"','"+passwordPegawaiField.getText()+"','"+kode+"')");
            } else{
                conn.query("UPDATE pegawai SET username='"+usernamePegawaiField.getText()+"', password='"+passwordPegawaiField.getText()+"', kode='"+kode+"' WHERE user_id='"+pilihPegawaiField.getText()+"'");
            }
        } catch (Exception e){}
        bersihPegawai();
        refreshPegawai();
        showPegawai();
    }//GEN-LAST:event_simpanPegawaiButtonActionPerformed

    private void baruPegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baruPegawaiButtonActionPerformed
        usernamePegawaiField.setEnabled(true);
        passwordPegawaiField.setEnabled(true);
        adminCheckBox.setEnabled(true);
        simpanPegawaiButton.setEnabled(true);
        hapusPegawaiButton.setEnabled(true);
        batalPegawaiButton.setEnabled(true);
        baruPegawaiButton.setEnabled(false);
        pilihPegawaiButton.setEnabled(false);
        pilihPegawaiField.setEnabled(false);
        pilihPegawaiField.setText("");
    }//GEN-LAST:event_baruPegawaiButtonActionPerformed

    private void batalPegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalPegawaiButtonActionPerformed
        bersihPegawai();
    }//GEN-LAST:event_batalPegawaiButtonActionPerformed

    private void pilihPegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihPegawaiButtonActionPerformed
        if (cekPegawai(pilihPegawaiField.getText())){
            String id = pilihPegawaiField.getText();
            ResultSet rs = null;
            try{
                Koneksi conn = new Koneksi();
                rs = conn.getData("SELECT * FROM pegawai WHERE user_id='"+id+"'");
                
                while (rs.next()){
                    usernamePegawaiField.setText(rs.getString("username"));
                    passwordPegawaiField.setText(rs.getString("password"));
                    if (rs.getInt("kode") == 1){
                        adminCheckBox.setSelected(true);
                    }
                    rs.close();
                }
            } catch (SQLException e) {}
            usernamePegawaiField.setEnabled(true);
            passwordPegawaiField.setEnabled(true);
            adminCheckBox.setEnabled(true);
            simpanPegawaiButton.setEnabled(true);
            hapusPegawaiButton.setEnabled(true);
            batalPegawaiButton.setEnabled(true);
            baruPegawaiButton.setEnabled(false);
            pilihPegawaiButton.setEnabled(false);
            pilihPegawaiField.setEnabled(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "ID tidak ditemukan");
        }
    }//GEN-LAST:event_pilihPegawaiButtonActionPerformed

    private void dataPegawaiPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_dataPegawaiPanelComponentShown
        showPegawai();
    }//GEN-LAST:event_dataPegawaiPanelComponentShown

    private void cariPegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariPegawaiButtonActionPerformed
        refreshPegawai();
        String query = cariPegawaiField.getText();
        int baris = 0;
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM pegawai WHERE username LIKE '%" + query + "%'");

            while (rs.next()){
                pegawaiTable.setValueAt(rs.getString("user_id"), baris, 0);
                pegawaiTable.setValueAt(rs.getString("username"), baris, 1);
                pegawaiTable.setValueAt(rs.getString("password"), baris, 2);
                pegawaiTable.setValueAt(rs.getString("kode"), baris, 3);
                baris++;
            }
            rs.close();
        } catch (SQLException e){}
    }//GEN-LAST:event_cariPegawaiButtonActionPerformed
   
    private boolean cekPelanggan(String id){
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM pelanggan WHERE pelanggan_id='"+id+"'");
            if (rs.next()){
                rs.close();
                return true;
            }
        } catch (SQLException e) {}
        return false;
    }

    private boolean cekKendaraan(String id){
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM kendaraan WHERE kendaraan_id='"+id+"'");
            if (rs.next()){
                rs.close();
                return true;
            }
        } catch (SQLException e) {}
        return false;
    }
    
    private boolean cekPegawai(String id){
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM pegawai WHERE user_id='"+id+"'");
            if (rs.next()){
                    rs.close();
                    return true;
            }
        } catch (SQLException e) {}
        return false;
    }
    
    private void refreshPelanggan(){
        for (int i=0; i<25; i++){
            for (int j=0; j<4; j++){
                pelangganTable.setValueAt("", i, j);
            }
        }
    }
    
    private void showPelanggan(){
        int baris = 0;
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM pelanggan");

            while (rs.next()){
                pelangganTable.setValueAt(rs.getString("pelanggan_id"), baris, 0);
                pelangganTable.setValueAt(rs.getString("nama"), baris, 1);
                pelangganTable.setValueAt(rs.getString("alamat"), baris, 2);
                pelangganTable.setValueAt(rs.getString("cp"), baris, 3);
                baris++;
            }
            rs.close();
        } catch (SQLException e){}
    }
    
    private void refreshKendaraan(){
        for (int i=0; i<25; i++){
            for (int j=0; j<4; j++){
                kendaraanTable.setValueAt("", i, j);
            }
        }
    }
    
    private void showKendaraan(){
        int baris = 0;
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM kendaraan");

            while (rs.next()){
                kendaraanTable.setValueAt(rs.getString("kendaraan_id"), baris, 0);
                kendaraanTable.setValueAt(rs.getString("jenis"), baris, 1);
                kendaraanTable.setValueAt(rs.getString("harga"), baris, 2);
                kendaraanTable.setValueAt(rs.getString("stok"), baris, 3);
                baris++;
            }
            rs.close();
        } catch (SQLException e){}
    }
    
    private void bersihPegawai(){
        usernamePegawaiField.setText("");
        usernamePegawaiField.setEnabled(false);
        passwordPegawaiField.setText("");
        passwordPegawaiField.setEnabled(false);
        adminCheckBox.setSelected(false);
        adminCheckBox.setEnabled(false);
        simpanPegawaiButton.setEnabled(false);
        hapusPegawaiButton.setEnabled(false);
        batalPegawaiButton.setEnabled(false);
        baruPegawaiButton.setEnabled(true);
        pilihPegawaiButton.setEnabled(true);
        pilihPegawaiField.setText("");
        pilihPegawaiField.setEnabled(true);
    }

    private void refreshPegawai(){
        for (int i=0; i<25; i++){
            for (int j=0; j<4; j++){
                pegawaiTable.setValueAt("", i, j);
            }
        }
    }
    
    private void showPegawai(){
        int baris = 0;
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM pegawai");

            while (rs.next()){
                pegawaiTable.setValueAt(rs.getString("user_id"), baris, 0);
                pegawaiTable.setValueAt(rs.getString("username"), baris, 1);
                pegawaiTable.setValueAt(rs.getString("password"), baris, 2);
                pegawaiTable.setValueAt(rs.getInt("kode"), baris, 3);
                baris++;
            }
            rs.close();
        } catch (SQLException e){}
    }
    
    private void bersihPeminjaman(){
        pelangganPeminjamanComboBox.setSelectedItem("");
        pelangganPeminjamanComboBox.setEnabled(true);
        jenisPeminjamanComboBox.setSelectedItem("");
        jenisPeminjamanComboBox.setEnabled(true);
        pegawaiPeminjamanComboBox.setSelectedItem("");
        pegawaiPeminjamanComboBox.setEnabled(true);
        tanggalPesanPeminjamanField.setText("");
        tanggalPesanPeminjamanField.setEnabled(true);
        lamaPeminjamanField.setText("");
        lamaPeminjamanField.setEnabled(true);
        biayaPeminjamanField.setText("");
        totalPeminjamanField.setText("");
        tanggalKembaliPeminjamanField.setText("");
        simpanPeminjamanButton.setEnabled(false);
        batalPeminjamanButton.setEnabled(false);
    }
    
    private void showTransaksi(){
        int baris = 0;
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM transaksi NATURAL JOIN pelanggan NATURAL JOIN kendaraan NATURAL JOIN pegawai");

            while (rs.next()){
                transaksiTable.setValueAt(rs.getString("transaksi_id"), baris, 0);
                transaksiTable.setValueAt(rs.getString("nama"), baris, 1);
                transaksiTable.setValueAt(rs.getString("jenis"), baris, 2);
                transaksiTable.setValueAt(rs.getString("username"), baris, 3);
                transaksiTable.setValueAt(rs.getDate("tanggal_pesan"), baris, 4);
                transaksiTable.setValueAt(rs.getDate("tanggal_kembali"), baris, 5);
                transaksiTable.setValueAt(rs.getString("lama_pinjam"), baris, 6);
                transaksiTable.setValueAt(rs.getString("total"), baris, 7);
                baris++;
            }
            rs.close();
        } catch (SQLException e){}
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rental().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox adminCheckBox;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JTextArea alamatTextArea;
    private javax.swing.JButton baruKendaraanButton;
    private javax.swing.JButton baruPegawaiButton;
    private javax.swing.JButton baruPelangganButton;
    private javax.swing.JButton batalKendaraanButton;
    private javax.swing.JButton batalPegawaiButton;
    private javax.swing.JButton batalPelangganButton;
    private javax.swing.JButton batalPeminjamanButton;
    private javax.swing.JTextField biayaPeminjamanField;
    private javax.swing.JLabel biayaPeminjamanLabel;
    private javax.swing.JLabel biayaPerHariPeminjamanLabel;
    private javax.swing.JButton cariPegawaiButton;
    private javax.swing.JTextField cariPegawaiField;
    private javax.swing.JButton cariPelangganButton;
    private javax.swing.JTextField cariPelangganField;
    private javax.swing.JTextField cpField;
    private javax.swing.JLabel cpLabel;
    private javax.swing.JPanel dataKendaraanPanel;
    private javax.swing.JPanel dataPegawaiPanel;
    private javax.swing.JPanel dataPelangganPanel;
    private javax.swing.JButton hapusKendaraanButton;
    private javax.swing.JButton hapusPegawaiButton;
    private javax.swing.JButton hapusPelangganButton;
    private javax.swing.JTextField hargaField;
    private javax.swing.JLabel hargaLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JTextArea homeTextArea;
    private javax.swing.JLabel idPelangganPeminjamanLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jenisField;
    private javax.swing.JLabel jenisLabel;
    private javax.swing.JComboBox<String> jenisPeminjamanComboBox;
    private javax.swing.JLabel jenisPeminjamanLabel;
    private javax.swing.JButton keluarButton;
    private javax.swing.JPanel kendaraanPanel;
    private javax.swing.JTable kendaraanTable;
    private javax.swing.JLabel lamaHariPeminjamanLabel;
    private javax.swing.JTextField lamaPeminjamanField;
    private javax.swing.JLabel lamaPeminjamanLabel;
    private javax.swing.JTextField namaPelangganField;
    private javax.swing.JLabel namaPelangganLabel;
    private javax.swing.JTextField passwordPegawaiField;
    private javax.swing.JLabel passwordPegawaiLabel;
    private javax.swing.JPanel pegawaiPanel;
    private javax.swing.JComboBox<String> pegawaiPeminjamanComboBox;
    private javax.swing.JLabel pegawaiPeminjamanLabel;
    private javax.swing.JTable pegawaiTable;
    private javax.swing.JPanel pelangganPanel;
    private javax.swing.JComboBox<String> pelangganPeminjamanComboBox;
    private javax.swing.JTable pelangganTable;
    private javax.swing.JPanel peminjamanPanel;
    private javax.swing.JPanel peminjamanPanel1;
    private javax.swing.JButton pilihKendaraanButton;
    private javax.swing.JTextField pilihKendaraanField;
    private javax.swing.JButton pilihPegawaiButton;
    private javax.swing.JTextField pilihPegawaiField;
    private javax.swing.JButton pilihPelangganButton;
    private javax.swing.JTextField pilihPelangganField;
    private javax.swing.JButton prosesButton;
    private javax.swing.JButton simpanKendaraanButton;
    private javax.swing.JButton simpanPegawaiButton;
    private javax.swing.JButton simpanPelangganButton;
    private javax.swing.JButton simpanPeminjamanButton;
    private javax.swing.JTextField stokField;
    private javax.swing.JLabel stokLabel;
    private javax.swing.JFormattedTextField tanggalKembaliPeminjamanField;
    private javax.swing.JLabel tanggalPesanLabel;
    private javax.swing.JLabel tanggalPesanLabel1;
    private javax.swing.JFormattedTextField tanggalPesanPeminjamanField;
    private javax.swing.JTextField totalPeminjamanField;
    private javax.swing.JLabel totalPeminjamanLabel;
    private javax.swing.JPanel transaksiPanel;
    private javax.swing.JTable transaksiTable;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField usernamePegawaiField;
    private javax.swing.JLabel usernamePegawaiLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
