/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import code.Koneksi;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.sql.*;

/**
 *
 * @author M13
 */
public class Rental extends javax.swing.JFrame {

    /**
     * Creates new form Rental
     */
    public Rental() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        homePanel = new javax.swing.JPanel();
        keluarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dataPelangganPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pelangganTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cariPelangganButton = new javax.swing.JButton();
        cariPelangganField = new javax.swing.JTextField();
        hapusPelangganButton = new javax.swing.JButton();
        namaPelangganLabel = new javax.swing.JLabel();
        namaPelangganField = new javax.swing.JTextField();
        alamatLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatTextArea = new javax.swing.JTextArea();
        cpLabel = new javax.swing.JLabel();
        cpField = new javax.swing.JTextField();
        simpanPelangganButton = new javax.swing.JButton();
        baruPelangganButton = new javax.swing.JButton();
        batalPelangganButton = new javax.swing.JButton();
        pilihPelangganButton = new javax.swing.JButton();
        pilihPelangganField = new javax.swing.JTextField();
        dataKendaraanPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        hapusKendaraanButton = new javax.swing.JButton();
        jenisLabel = new javax.swing.JLabel();
        jenisField = new javax.swing.JTextField();
        hargaLabel = new javax.swing.JLabel();
        stokLabel = new javax.swing.JLabel();
        stokField = new javax.swing.JTextField();
        simpanKendaraanButton = new javax.swing.JButton();
        baruKendaraanButton = new javax.swing.JButton();
        batalKendaraanButton = new javax.swing.JButton();
        pilihKendaraanButton = new javax.swing.JButton();
        pilihKendaraanField = new javax.swing.JTextField();
        hargaField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        kendaraanTable = new javax.swing.JTable();
        peminjamanPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        idPelangganPeminjamanLabel = new javax.swing.JLabel();
        idPelangganPeminjamanField = new javax.swing.JTextField();
        jenisPeminjamanLabel = new javax.swing.JLabel();
        jenisPeminjamanComboBox = new javax.swing.JComboBox<>();
        tanggalPesanLabel = new javax.swing.JLabel();
        tanggalPesanPeminjamanField = new javax.swing.JFormattedTextField();
        lamaPeminjamanLabel = new javax.swing.JLabel();
        lamaPeminjamanField = new javax.swing.JTextField();
        prosesButton = new javax.swing.JButton();
        biayaPeminjamanLabel = new javax.swing.JLabel();
        biayaPeminjamanField = new javax.swing.JTextField();
        totalPeminjamanLabel = new javax.swing.JLabel();
        totalPeminjamanField = new javax.swing.JTextField();
        lamaHariPeminjamanLabel = new javax.swing.JLabel();
        biayaPerHariPeminjamanLabel = new javax.swing.JLabel();
        tanggalPesanLabel1 = new javax.swing.JLabel();
        tanggalKembaliPeminjamanField = new javax.swing.JFormattedTextField();
        simpanPeminjamanButton = new javax.swing.JButton();
        batalPeminjamanButton = new javax.swing.JButton();
        transaksiPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        transaksiTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        keluarButton.setText("Keluar");
        keluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Fira Code", 0, 36)); // NOI18N
        jLabel1.setText("Selamat Datang");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(keluarButton)
                .addContainerGap())
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 392, Short.MAX_VALUE)
                .addComponent(keluarButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Home", homePanel);

        dataPelangganPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                dataPelangganPanelComponentShown(evt);
            }
        });

        pelangganTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Alamat", "Contact Person"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pelangganTable.setToolTipText("");
        jScrollPane1.setViewportView(pelangganTable);
        if (pelangganTable.getColumnModel().getColumnCount() > 0) {
            pelangganTable.getColumnModel().getColumn(0).setPreferredWidth(15);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        cariPelangganButton.setText("Cari (Nama)");
        cariPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariPelangganButtonActionPerformed(evt);
            }
        });

        hapusPelangganButton.setText("Hapus");
        hapusPelangganButton.setEnabled(false);
        hapusPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPelangganButtonActionPerformed(evt);
            }
        });

        namaPelangganLabel.setText("Nama:");

        namaPelangganField.setEnabled(false);

        alamatLabel.setText("Alamat:");

        alamatTextArea.setColumns(20);
        alamatTextArea.setRows(5);
        alamatTextArea.setEnabled(false);
        jScrollPane2.setViewportView(alamatTextArea);

        cpLabel.setText("Contact Person:");

        cpField.setEnabled(false);

        simpanPelangganButton.setText("Simpan");
        simpanPelangganButton.setEnabled(false);
        simpanPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPelangganButtonActionPerformed(evt);
            }
        });

        baruPelangganButton.setText("Baru");
        baruPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baruPelangganButtonActionPerformed(evt);
            }
        });

        batalPelangganButton.setText("Batal");
        batalPelangganButton.setEnabled(false);
        batalPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalPelangganButtonActionPerformed(evt);
            }
        });

        pilihPelangganButton.setText("Pilih (ID)");
        pilihPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihPelangganButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(baruPelangganButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simpanPelangganButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapusPelangganButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(batalPelangganButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alamatLabel)
                            .addComponent(namaPelangganLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpLabel))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(namaPelangganField)
                            .addComponent(cpField))
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pilihPelangganButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cariPelangganButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pilihPelangganField)
                            .addComponent(cariPelangganField))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPelangganLabel)
                    .addComponent(namaPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamatLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpLabel)
                    .addComponent(cpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanPelangganButton)
                    .addComponent(baruPelangganButton)
                    .addComponent(batalPelangganButton)
                    .addComponent(hapusPelangganButton))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihPelangganButton)
                    .addComponent(pilihPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariPelangganButton)
                    .addComponent(cariPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout dataPelangganPanelLayout = new javax.swing.GroupLayout(dataPelangganPanel);
        dataPelangganPanel.setLayout(dataPelangganPanelLayout);
        dataPelangganPanelLayout.setHorizontalGroup(
            dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        dataPelangganPanelLayout.setVerticalGroup(
            dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data Pelanggan", dataPelangganPanel);

        dataKendaraanPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                dataKendaraanPanelComponentShown(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        hapusKendaraanButton.setText("Hapus");
        hapusKendaraanButton.setEnabled(false);
        hapusKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusKendaraanButtonActionPerformed(evt);
            }
        });

        jenisLabel.setText("Jenis:");

        jenisField.setEnabled(false);

        hargaLabel.setText("Harga:");

        stokLabel.setText("Stok:");

        stokField.setEnabled(false);

        simpanKendaraanButton.setText("Simpan");
        simpanKendaraanButton.setEnabled(false);
        simpanKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanKendaraanButtonActionPerformed(evt);
            }
        });

        baruKendaraanButton.setText("Baru");
        baruKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baruKendaraanButtonActionPerformed(evt);
            }
        });

        batalKendaraanButton.setText("Batal");
        batalKendaraanButton.setEnabled(false);
        batalKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalKendaraanButtonActionPerformed(evt);
            }
        });

        pilihKendaraanButton.setText("Pilih (ID)");
        pilihKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihKendaraanButtonActionPerformed(evt);
            }
        });

        hargaField.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(baruKendaraanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simpanKendaraanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapusKendaraanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(batalKendaraanButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hargaLabel)
                            .addComponent(jenisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stokLabel))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hargaField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stokField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jenisField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pilihKendaraanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pilihKendaraanField)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisLabel)
                    .addComponent(jenisField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaLabel)
                    .addComponent(hargaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stokLabel)
                    .addComponent(stokField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanKendaraanButton)
                    .addComponent(baruKendaraanButton)
                    .addComponent(batalKendaraanButton)
                    .addComponent(hapusKendaraanButton))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihKendaraanButton)
                    .addComponent(pilihKendaraanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kendaraanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Jenis", "Sewa", "Stok"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(kendaraanTable);

        javax.swing.GroupLayout dataKendaraanPanelLayout = new javax.swing.GroupLayout(dataKendaraanPanel);
        dataKendaraanPanel.setLayout(dataKendaraanPanelLayout);
        dataKendaraanPanelLayout.setHorizontalGroup(
            dataKendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataKendaraanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataKendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        dataKendaraanPanelLayout.setVerticalGroup(
            dataKendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataKendaraanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data Kendaraan", dataKendaraanPanel);

        peminjamanPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                peminjamanPanelComponentShown(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        idPelangganPeminjamanLabel.setText("ID Pelanggan:");

        jenisPeminjamanLabel.setText("Jenis:");

        tanggalPesanLabel.setText("Tanggal Pesan:");

        tanggalPesanPeminjamanField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        lamaPeminjamanLabel.setText("Lama Pinjam:");

        prosesButton.setText("Proses");
        prosesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesButtonActionPerformed(evt);
            }
        });

        biayaPeminjamanLabel.setText("Biaya Sewa:");

        biayaPeminjamanField.setEditable(false);

        totalPeminjamanLabel.setText("Total Sewa:");

        totalPeminjamanField.setEditable(false);

        lamaHariPeminjamanLabel.setText("hari");

        biayaPerHariPeminjamanLabel.setText("per hari");

        tanggalPesanLabel1.setText("Tanggal Kembali:");

        tanggalKembaliPeminjamanField.setEditable(false);
        tanggalKembaliPeminjamanField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        simpanPeminjamanButton.setText("Simpan");
        simpanPeminjamanButton.setEnabled(false);
        simpanPeminjamanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPeminjamanButtonActionPerformed(evt);
            }
        });

        batalPeminjamanButton.setText("Batal");
        batalPeminjamanButton.setEnabled(false);
        batalPeminjamanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalPeminjamanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prosesButton)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(simpanPeminjamanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(batalPeminjamanButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tanggalPesanLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jenisPeminjamanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tanggalPesanLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lamaPeminjamanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(biayaPeminjamanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalPeminjamanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idPelangganPeminjamanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tanggalPesanPeminjamanField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jenisPeminjamanComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 84, Short.MAX_VALUE)
                                .addComponent(idPelangganPeminjamanField, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tanggalKembaliPeminjamanField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                    .addComponent(lamaPeminjamanField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(biayaPeminjamanField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalPeminjamanField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lamaHariPeminjamanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(biayaPerHariPeminjamanLabel))))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idPelangganPeminjamanLabel)
                    .addComponent(idPelangganPeminjamanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisPeminjamanLabel)
                    .addComponent(jenisPeminjamanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggalPesanLabel)
                    .addComponent(tanggalPesanPeminjamanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lamaPeminjamanLabel)
                    .addComponent(lamaPeminjamanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lamaHariPeminjamanLabel))
                .addGap(18, 18, 18)
                .addComponent(prosesButton)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(biayaPeminjamanLabel)
                    .addComponent(biayaPeminjamanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biayaPerHariPeminjamanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPeminjamanLabel)
                    .addComponent(totalPeminjamanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggalPesanLabel1)
                    .addComponent(tanggalKembaliPeminjamanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanPeminjamanButton)
                    .addComponent(batalPeminjamanButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout peminjamanPanelLayout = new javax.swing.GroupLayout(peminjamanPanel);
        peminjamanPanel.setLayout(peminjamanPanelLayout);
        peminjamanPanelLayout.setHorizontalGroup(
            peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peminjamanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        peminjamanPanelLayout.setVerticalGroup(
            peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peminjamanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Peminjaman", peminjamanPanel);

        transaksiPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                transaksiPanelComponentShown(evt);
            }
        });

        transaksiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Pelanggan", "Kendaraan", "Tanggal Pesan", "Tanggal Kembali", "Lama Pinjam", "Total"
            }
        ));
        jScrollPane4.setViewportView(transaksiTable);

        javax.swing.GroupLayout transaksiPanelLayout = new javax.swing.GroupLayout(transaksiPanel);
        transaksiPanel.setLayout(transaksiPanelLayout);
        transaksiPanelLayout.setHorizontalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
        );
        transaksiPanelLayout.setVerticalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Transaksi", transaksiPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void dataPelangganPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_dataPelangganPanelComponentShown
        showPelanggan();
    }//GEN-LAST:event_dataPelangganPanelComponentShown

    private void hapusPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPelangganButtonActionPerformed
        String query = pilihPelangganField.getText();
        try {
            Koneksi conn = new Koneksi();
            conn.query("DELETE FROM pelanggan WHERE pelanggan_id = '" + query + "'");
        } catch (Exception e){}
        namaPelangganField.setText("");
        namaPelangganField.setEnabled(false);
        alamatTextArea.setText("");
        alamatTextArea.setEnabled(false);
        cpField.setText("");
        cpField.setEnabled(false);
        simpanPelangganButton.setEnabled(false);
        hapusPelangganButton.setEnabled(false);
        batalPelangganButton.setEnabled(false);
        baruPelangganButton.setEnabled(true);
        pilihPelangganButton.setEnabled(true);
        pilihPelangganField.setText("");
        pilihPelangganField.setEnabled(true);
        refreshPelanggan();
        showPelanggan();
    }//GEN-LAST:event_hapusPelangganButtonActionPerformed

    private void cariPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariPelangganButtonActionPerformed
        refreshPelanggan();
        String query = cariPelangganField.getText();
        int baris = 0;
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM pelanggan WHERE nama LIKE '%" + query + "%'");

            while (rs.next()){
                pelangganTable.setValueAt(rs.getString("pelanggan_id"), baris, 0);
                pelangganTable.setValueAt(rs.getString("nama"), baris, 1);
                pelangganTable.setValueAt(rs.getString("alamat"), baris, 2);
                pelangganTable.setValueAt(rs.getString("cp"), baris, 3);
                baris++;
            }
            rs.close();
        } catch (SQLException e){}
    }//GEN-LAST:event_cariPelangganButtonActionPerformed

    private void simpanPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPelangganButtonActionPerformed
        try {
            Koneksi conn = new Koneksi();
            if (pilihPelangganField.getText().equals("")){
                conn.query("INSERT INTO pelanggan (nama, alamat, cp) VALUES ('"+namaPelangganField.getText()+"','"+alamatTextArea.getText()+"','"+cpField.getText()+"')");
            } else{
                conn.query("UPDATE pelanggan SET nama='"+namaPelangganField.getText()+"', alamat='"+alamatTextArea.getText()+"', cp='"+cpField.getText()+"' WHERE pelanggan_id='"+pilihPelangganField.getText()+"'");
            }
        } catch (Exception e){}
        namaPelangganField.setText("");
        namaPelangganField.setEnabled(false);
        alamatTextArea.setText("");
        alamatTextArea.setEnabled(false);
        cpField.setText("");
        cpField.setEnabled(false);
        simpanPelangganButton.setEnabled(false);
        hapusPelangganButton.setEnabled(false);
        batalPelangganButton.setEnabled(false);
        baruPelangganButton.setEnabled(true);
        pilihPelangganButton.setEnabled(true);
        pilihPelangganField.setText("");
        pilihPelangganField.setEnabled(true);
        refreshPelanggan();
        showPelanggan();
    }//GEN-LAST:event_simpanPelangganButtonActionPerformed

    private void baruPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baruPelangganButtonActionPerformed
        namaPelangganField.setEnabled(true);
        alamatTextArea.setEnabled(true);
        cpField.setEnabled(true);
        simpanPelangganButton.setEnabled(true);
        batalPelangganButton.setEnabled(true);
        baruPelangganButton.setEnabled(false);
        pilihPelangganButton.setEnabled(false);
        pilihPelangganField.setText("");
        pilihPelangganField.setEnabled(false);
    }//GEN-LAST:event_baruPelangganButtonActionPerformed

    private void batalPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalPelangganButtonActionPerformed
        namaPelangganField.setText("");
        namaPelangganField.setEnabled(false);
        alamatTextArea.setText("");
        alamatTextArea.setEnabled(false);
        cpField.setText("");
        cpField.setEnabled(false);
        simpanPelangganButton.setEnabled(false);
        hapusPelangganButton.setEnabled(false);
        batalPelangganButton.setEnabled(false);
        baruPelangganButton.setEnabled(true);
        pilihPelangganButton.setEnabled(true);
        pilihPelangganField.setEnabled(true);
    }//GEN-LAST:event_batalPelangganButtonActionPerformed

    private void pilihPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihPelangganButtonActionPerformed
        if (cekPelanggan(pilihPelangganField.getText())){
            String id = pilihPelangganField.getText();
            ResultSet rs = null;
            try{
                Koneksi conn = new Koneksi();
                rs = conn.getData("SELECT * FROM pelanggan WHERE pelanggan_id='"+id+"'");
                
                while (rs.next()){
                    namaPelangganField.setText(rs.getString("nama"));
                    alamatTextArea.setText(rs.getString("alamat"));
                    cpField.setText(rs.getString("cp"));
                }
                rs.close();
            } catch (SQLException e) {}
            namaPelangganField.setEnabled(true);
            alamatTextArea.setEnabled(true);
            cpField.setEnabled(true);
            simpanPelangganButton.setEnabled(true);
            hapusPelangganButton.setEnabled(true);
            batalPelangganButton.setEnabled(true);
            baruPelangganButton.setEnabled(false);
            pilihPelangganButton.setEnabled(false);
            pilihPelangganField.setEnabled(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "ID tidak ditemukan");
        }
    }//GEN-LAST:event_pilihPelangganButtonActionPerformed

    private void keluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarButtonActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_keluarButtonActionPerformed

    private void hapusKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusKendaraanButtonActionPerformed
        String query = pilihKendaraanField.getText();
        try {
            Koneksi conn = new Koneksi();
            conn.query("DELETE FROM kendaraan WHERE kendaraan_id = '" + query + "'");
        } catch (Exception e){}
        jenisField.setText("");
        jenisField.setEnabled(false);
        hargaField.setText("");
        hargaField.setEnabled(false);
        stokField.setText("");
        stokField.setEnabled(false);
        simpanKendaraanButton.setEnabled(false);
        hapusKendaraanButton.setEnabled(false);
        batalKendaraanButton.setEnabled(false);
        baruKendaraanButton.setEnabled(true);
        pilihKendaraanButton.setEnabled(true);
        pilihKendaraanField.setText("");
        pilihKendaraanField.setEnabled(true);
        refreshKendaraan();
        showKendaraan();
    }//GEN-LAST:event_hapusKendaraanButtonActionPerformed

    private void simpanKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanKendaraanButtonActionPerformed
        try {
            Koneksi conn = new Koneksi();
            if (pilihKendaraanField.getText().equals("")){
                conn.query("INSERT INTO kendaraan (jenis, harga, stok) VALUES ('"+jenisField.getText()+"','"+hargaField.getText()+"','"+stokField.getText()+"')");
            } else{
                conn.query("UPDATE kendaraan SET jenis='"+jenisField.getText()+"', harga='"+hargaField.getText()+"', stok='"+stokField.getText()+"' WHERE kendaraan_id='"+pilihKendaraanField.getText()+"'");
            }
        } catch (Exception e){}
        jenisField.setText("");
        jenisField.setEnabled(false);
        hargaField.setText("");
        hargaField.setEnabled(false);
        stokField.setText("");
        stokField.setEnabled(false);
        simpanKendaraanButton.setEnabled(false);
        hapusKendaraanButton.setEnabled(false);
        batalKendaraanButton.setEnabled(false);
        baruKendaraanButton.setEnabled(true);
        pilihKendaraanButton.setEnabled(true);
        pilihKendaraanField.setText("");
        pilihKendaraanField.setEnabled(true);
        refreshKendaraan();
        showKendaraan();
    }//GEN-LAST:event_simpanKendaraanButtonActionPerformed

    private void baruKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baruKendaraanButtonActionPerformed
        jenisField.setEnabled(true);
        hargaField.setEnabled(true);
        stokField.setEnabled(true);
        simpanKendaraanButton.setEnabled(true);
        batalKendaraanButton.setEnabled(true);
        baruKendaraanButton.setEnabled(false);
        pilihKendaraanButton.setEnabled(false);
        pilihKendaraanField.setText("");
        pilihKendaraanField.setEnabled(false);
    }//GEN-LAST:event_baruKendaraanButtonActionPerformed

    private void batalKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalKendaraanButtonActionPerformed
        jenisField.setText("");
        jenisField.setEnabled(false);
        hargaField.setText("");
        hargaField.setEnabled(false);
        stokField.setText("");
        stokField.setEnabled(false);
        simpanKendaraanButton.setEnabled(false);
        hapusKendaraanButton.setEnabled(false);
        batalKendaraanButton.setEnabled(false);
        baruKendaraanButton.setEnabled(true);
        pilihKendaraanButton.setEnabled(true);
        pilihKendaraanField.setEnabled(true);
    }//GEN-LAST:event_batalKendaraanButtonActionPerformed

    private void pilihKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihKendaraanButtonActionPerformed
        if (cekKendaraan(pilihKendaraanField.getText())){
            String id = pilihKendaraanField.getText();
            ResultSet rs = null;
            try{
                Koneksi conn = new Koneksi();
                rs = conn.getData("SELECT * FROM kendaraan WHERE kendaraan_id='"+id+"'");
                
                while (rs.next()){
                    jenisField.setText(rs.getString("jenis"));
                    hargaField.setText(rs.getString("harga"));
                    stokField.setText(rs.getString("stok"));
                    rs.close();
                }
            } catch (SQLException e) {}
            jenisField.setEnabled(true);
            hargaField.setEnabled(true);
            stokField.setEnabled(true);
            simpanKendaraanButton.setEnabled(true);
            hapusKendaraanButton.setEnabled(true);
            batalKendaraanButton.setEnabled(true);
            baruKendaraanButton.setEnabled(false);
            pilihKendaraanButton.setEnabled(false);
            pilihKendaraanField.setEnabled(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "ID tidak ditemukan");
        }
    }//GEN-LAST:event_pilihKendaraanButtonActionPerformed

    private void peminjamanPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_peminjamanPanelComponentShown
        jenisPeminjamanComboBox.removeAllItems();
        jenisPeminjamanComboBox.addItem("");
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM kendaraan");
            
            while(rs.next()) {
                jenisPeminjamanComboBox.addItem(rs.getString("jenis"));
            }
            rs.close();
        } catch(SQLException e) {}
    }//GEN-LAST:event_peminjamanPanelComponentShown

    private void prosesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesButtonActionPerformed
        if (cekPelanggan(idPelangganPeminjamanField.getText())){
            idPelangganPeminjamanField.setEnabled(false);
            jenisPeminjamanComboBox.setEnabled(false);
            tanggalPesanPeminjamanField.setEnabled(false);
            lamaPeminjamanField.setEnabled(false);
            int sewa = 0;
            try {
                Koneksi conn = new Koneksi();
                ResultSet rs = null;
                rs = conn.getData("SELECT * FROM kendaraan WHERE jenis='"+jenisPeminjamanComboBox.getSelectedItem()+"'");
                rs.next();
                biayaPeminjamanField.setText(rs.getString("harga"));            
                sewa = Integer.parseInt(rs.getString("harga"));
                rs.close();
            } catch (SQLException e) {}
            
            int lama = Integer.parseInt(lamaPeminjamanField.getText());
            totalPeminjamanField.setText(Integer.toString(lama*sewa));
            
            SimpleDateFormat formatTanggal = new SimpleDateFormat("dd/MM/yyyy");
            Calendar cal = Calendar.getInstance();
            try {
                cal.setTime(formatTanggal.parse(tanggalPesanPeminjamanField.getText()));
                cal.add(Calendar.DATE, lama);
                String output = formatTanggal.format(cal.getTime());
                tanggalKembaliPeminjamanField.setText(output);
            } catch (ParseException e){}
            
            simpanPeminjamanButton.setEnabled(true);
            batalPeminjamanButton.setEnabled(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "ID tidak ditemukan");
        }
    }//GEN-LAST:event_prosesButtonActionPerformed

    private void simpanPeminjamanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPeminjamanButtonActionPerformed
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM kendaraan WHERE jenis='"+jenisPeminjamanComboBox.getSelectedItem()+"'");
            rs.next();
            String kendaraan_id = rs.getString("kendaraan_id");         
            rs.close();
            
            String pesanFormatted = tanggalPesanPeminjamanField.getText();
            String[] pesanSplit = pesanFormatted.split("/");
            pesanFormatted = pesanSplit[2]+"-"+pesanSplit[1]+"-"+pesanSplit[0];
            String kembaliFormatted = tanggalKembaliPeminjamanField.getText();
            String[] kembaliSplit = kembaliFormatted.split("/");
            kembaliFormatted = kembaliSplit[2]+"-"+kembaliSplit[1]+"-"+kembaliSplit[0];
            String query = "INSERT INTO transaksi (pelanggan_id, kendaraan_id, tanggal_pesan, tanggal_kembali, lama_pinjam, total) "
                    + "VALUES ('"+idPelangganPeminjamanField.getText()+"','"+kendaraan_id+"','"+pesanFormatted+"','"+kembaliFormatted+"','"+lamaPeminjamanField.getText()+"','"+totalPeminjamanField.getText()+"')";
            conn.query(query);
            
            bersihPeminjaman();
        } catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_simpanPeminjamanButtonActionPerformed

    private void dataKendaraanPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_dataKendaraanPanelComponentShown
        showKendaraan();
    }//GEN-LAST:event_dataKendaraanPanelComponentShown

    private void transaksiPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_transaksiPanelComponentShown
        showTransaksi();
    }//GEN-LAST:event_transaksiPanelComponentShown

    private void batalPeminjamanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalPeminjamanButtonActionPerformed
        bersihPeminjaman();
    }//GEN-LAST:event_batalPeminjamanButtonActionPerformed
   
    private boolean cekPelanggan(String id){
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM pelanggan WHERE pelanggan_id='"+id+"'");
            if (rs.next()){
                rs.close();
                return true;
            }
        } catch (SQLException e) {}
        return false;
    }

    private boolean cekKendaraan(String id){
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM kendaraan WHERE kendaraan_id='"+id+"'");
            if (rs.next()){
                rs.close();
                return true;
            }
        } catch (SQLException e) {}
        return false;
    }
    
    private void refreshPelanggan(){
        for (int i=0; i<10; i++){
            for (int j=0; j<4; j++){
                pelangganTable.setValueAt("", i, j);
            }
        }
    }
    
    private void showPelanggan(){
        int baris = 0;
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM pelanggan");

            while (rs.next()){
                pelangganTable.setValueAt(rs.getString("pelanggan_id"), baris, 0);
                pelangganTable.setValueAt(rs.getString("nama"), baris, 1);
                pelangganTable.setValueAt(rs.getString("alamat"), baris, 2);
                pelangganTable.setValueAt(rs.getString("cp"), baris, 3);
                baris++;
            }
            rs.close();
        } catch (SQLException e){}
    }
    
    private void refreshKendaraan(){
        for (int i=0; i<10; i++){
            for (int j=0; j<4; j++){
                kendaraanTable.setValueAt("", i, j);
            }
        }
    }
    
    private void showKendaraan(){
        int baris = 0;
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM kendaraan");

            while (rs.next()){
                kendaraanTable.setValueAt(rs.getString("kendaraan_id"), baris, 0);
                kendaraanTable.setValueAt(rs.getString("jenis"), baris, 1);
                kendaraanTable.setValueAt(rs.getString("harga"), baris, 2);
                kendaraanTable.setValueAt(rs.getString("stok"), baris, 3);
                baris++;
            }
            rs.close();
        } catch (SQLException e){}
    }
    
    private void bersihPeminjaman(){
        idPelangganPeminjamanField.setText("");
        idPelangganPeminjamanField.setEnabled(true);
        jenisPeminjamanComboBox.setSelectedItem("");
        jenisPeminjamanComboBox.setEnabled(true);
        tanggalPesanPeminjamanField.setText("");
        tanggalPesanPeminjamanField.setEnabled(true);
        lamaPeminjamanField.setText("");
        lamaPeminjamanField.setEnabled(true);
        biayaPeminjamanField.setText("");
        totalPeminjamanField.setText("");
        tanggalKembaliPeminjamanField.setText("");
        simpanPeminjamanButton.setEnabled(false);
        batalPeminjamanButton.setEnabled(false);
    }
    
    private void showTransaksi(){
        int baris = 0;
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM transaksi");

            while (rs.next()){
                transaksiTable.setValueAt(rs.getString("transaksi_id"), baris, 0);
                transaksiTable.setValueAt(rs.getString("pelanggan_id"), baris, 1);
                transaksiTable.setValueAt(rs.getString("kendaraan_id"), baris, 2);
                transaksiTable.setValueAt(rs.getDate("tanggal_pesan"), baris, 3);
                transaksiTable.setValueAt(rs.getDate("tanggal_kembali"), baris, 4);
                transaksiTable.setValueAt(rs.getString("lama_pinjam"), baris, 5);
                transaksiTable.setValueAt(rs.getString("total"), baris, 6);
                baris++;
            }
            rs.close();
        } catch (SQLException e){}
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rental().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JTextArea alamatTextArea;
    private javax.swing.JButton baruKendaraanButton;
    private javax.swing.JButton baruPelangganButton;
    private javax.swing.JButton batalKendaraanButton;
    private javax.swing.JButton batalPelangganButton;
    private javax.swing.JButton batalPeminjamanButton;
    private javax.swing.JTextField biayaPeminjamanField;
    private javax.swing.JLabel biayaPeminjamanLabel;
    private javax.swing.JLabel biayaPerHariPeminjamanLabel;
    private javax.swing.JButton cariPelangganButton;
    private javax.swing.JTextField cariPelangganField;
    private javax.swing.JTextField cpField;
    private javax.swing.JLabel cpLabel;
    private javax.swing.JPanel dataKendaraanPanel;
    private javax.swing.JPanel dataPelangganPanel;
    private javax.swing.JButton hapusKendaraanButton;
    private javax.swing.JButton hapusPelangganButton;
    private javax.swing.JTextField hargaField;
    private javax.swing.JLabel hargaLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JTextField idPelangganPeminjamanField;
    private javax.swing.JLabel idPelangganPeminjamanLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jenisField;
    private javax.swing.JLabel jenisLabel;
    private javax.swing.JComboBox<String> jenisPeminjamanComboBox;
    private javax.swing.JLabel jenisPeminjamanLabel;
    private javax.swing.JButton keluarButton;
    private javax.swing.JTable kendaraanTable;
    private javax.swing.JLabel lamaHariPeminjamanLabel;
    private javax.swing.JTextField lamaPeminjamanField;
    private javax.swing.JLabel lamaPeminjamanLabel;
    private javax.swing.JTextField namaPelangganField;
    private javax.swing.JLabel namaPelangganLabel;
    private javax.swing.JTable pelangganTable;
    private javax.swing.JPanel peminjamanPanel;
    private javax.swing.JButton pilihKendaraanButton;
    private javax.swing.JTextField pilihKendaraanField;
    private javax.swing.JButton pilihPelangganButton;
    private javax.swing.JTextField pilihPelangganField;
    private javax.swing.JButton prosesButton;
    private javax.swing.JButton simpanKendaraanButton;
    private javax.swing.JButton simpanPelangganButton;
    private javax.swing.JButton simpanPeminjamanButton;
    private javax.swing.JTextField stokField;
    private javax.swing.JLabel stokLabel;
    private javax.swing.JFormattedTextField tanggalKembaliPeminjamanField;
    private javax.swing.JLabel tanggalPesanLabel;
    private javax.swing.JLabel tanggalPesanLabel1;
    private javax.swing.JFormattedTextField tanggalPesanPeminjamanField;
    private javax.swing.JTextField totalPeminjamanField;
    private javax.swing.JLabel totalPeminjamanLabel;
    private javax.swing.JPanel transaksiPanel;
    private javax.swing.JTable transaksiTable;
    // End of variables declaration//GEN-END:variables
}
