/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import code.Koneksi;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author M13
 */
public class Rental extends javax.swing.JFrame {

    /**
     * Creates new form Rental
     */
    public Rental() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        homePanel = new javax.swing.JPanel();
        keluarButton = new javax.swing.JButton();
        dataPelangganPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        testTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cariPelangganButton = new javax.swing.JButton();
        cariPelangganField = new javax.swing.JTextField();
        hapusPelangganButton = new javax.swing.JButton();
        namaPelangganLabel = new javax.swing.JLabel();
        namaPelangganField = new javax.swing.JTextField();
        alamatLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatTextArea = new javax.swing.JTextArea();
        cpLabel = new javax.swing.JLabel();
        cpField = new javax.swing.JTextField();
        simpanPelangganButton = new javax.swing.JButton();
        baruPelangganButton = new javax.swing.JButton();
        batalPelangganButton = new javax.swing.JButton();
        pilihPelangganButton = new javax.swing.JButton();
        pilihPelangganField = new javax.swing.JTextField();
        dataKendaraanPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        hapusKendaraanButton = new javax.swing.JButton();
        jenisLabel = new javax.swing.JLabel();
        jenisField = new javax.swing.JTextField();
        hargaLabel = new javax.swing.JLabel();
        stokLabel = new javax.swing.JLabel();
        stokField = new javax.swing.JTextField();
        simpanKendaraanButton = new javax.swing.JButton();
        baruKendaraanButton = new javax.swing.JButton();
        batalKendaraanButton = new javax.swing.JButton();
        pilihKendaraanButton = new javax.swing.JButton();
        pilihKendaraanField = new javax.swing.JTextField();
        hargaField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        keluarButton.setText("Keluar");
        keluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addComponent(keluarButton)
                .addContainerGap())
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(442, Short.MAX_VALUE)
                .addComponent(keluarButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Home", homePanel);

        dataPelangganPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                dataPelangganPanelComponentShown(evt);
            }
        });

        testTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Alamat", "Contact Person"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        testTable.setToolTipText("");
        jScrollPane1.setViewportView(testTable);
        if (testTable.getColumnModel().getColumnCount() > 0) {
            testTable.getColumnModel().getColumn(0).setPreferredWidth(15);
        }

        cariPelangganButton.setText("Cari (Nama)");
        cariPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariPelangganButtonActionPerformed(evt);
            }
        });

        hapusPelangganButton.setText("Hapus");
        hapusPelangganButton.setEnabled(false);
        hapusPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPelangganButtonActionPerformed(evt);
            }
        });

        namaPelangganLabel.setText("Nama:");

        alamatLabel.setText("Alamat:");

        alamatTextArea.setColumns(20);
        alamatTextArea.setRows(5);
        jScrollPane2.setViewportView(alamatTextArea);

        cpLabel.setText("Contact Person:");

        simpanPelangganButton.setText("Simpan");
        simpanPelangganButton.setEnabled(false);
        simpanPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPelangganButtonActionPerformed(evt);
            }
        });

        baruPelangganButton.setText("Baru");
        baruPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baruPelangganButtonActionPerformed(evt);
            }
        });

        batalPelangganButton.setText("Batal");
        batalPelangganButton.setEnabled(false);
        batalPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalPelangganButtonActionPerformed(evt);
            }
        });

        pilihPelangganButton.setText("Pilih (ID)");
        pilihPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihPelangganButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(baruPelangganButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simpanPelangganButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapusPelangganButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(batalPelangganButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alamatLabel)
                            .addComponent(namaPelangganLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpLabel))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(namaPelangganField)
                            .addComponent(cpField))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pilihPelangganButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cariPelangganButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cariPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pilihPelangganField, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPelangganLabel)
                    .addComponent(namaPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamatLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpLabel)
                    .addComponent(cpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanPelangganButton)
                    .addComponent(baruPelangganButton)
                    .addComponent(batalPelangganButton)
                    .addComponent(hapusPelangganButton))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihPelangganButton)
                    .addComponent(pilihPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariPelangganButton)
                    .addComponent(cariPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout dataPelangganPanelLayout = new javax.swing.GroupLayout(dataPelangganPanel);
        dataPelangganPanel.setLayout(dataPelangganPanelLayout);
        dataPelangganPanelLayout.setHorizontalGroup(
            dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        dataPelangganPanelLayout.setVerticalGroup(
            dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data Pelanggan", dataPelangganPanel);

        hapusKendaraanButton.setText("Hapus");
        hapusKendaraanButton.setEnabled(false);
        hapusKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusKendaraanButtonActionPerformed(evt);
            }
        });

        jenisLabel.setText("Jenis:");

        hargaLabel.setText("Harga:");

        stokLabel.setText("Stok:");

        simpanKendaraanButton.setText("Simpan");
        simpanKendaraanButton.setEnabled(false);
        simpanKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanKendaraanButtonActionPerformed(evt);
            }
        });

        baruKendaraanButton.setText("Baru");
        baruKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baruKendaraanButtonActionPerformed(evt);
            }
        });

        batalKendaraanButton.setText("Batal");
        batalKendaraanButton.setEnabled(false);
        batalKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalKendaraanButtonActionPerformed(evt);
            }
        });

        pilihKendaraanButton.setText("Pilih (ID)");
        pilihKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihKendaraanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(baruKendaraanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simpanKendaraanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapusKendaraanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(batalKendaraanButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hargaLabel)
                            .addComponent(jenisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stokLabel))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hargaField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stokField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jenisField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pilihKendaraanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pilihKendaraanField)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisLabel)
                    .addComponent(jenisField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hargaLabel)
                    .addComponent(hargaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stokLabel)
                    .addComponent(stokField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanKendaraanButton)
                    .addComponent(baruKendaraanButton)
                    .addComponent(batalKendaraanButton)
                    .addComponent(hapusKendaraanButton))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihKendaraanButton)
                    .addComponent(pilihKendaraanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );

        javax.swing.GroupLayout dataKendaraanPanelLayout = new javax.swing.GroupLayout(dataKendaraanPanel);
        dataKendaraanPanel.setLayout(dataKendaraanPanelLayout);
        dataKendaraanPanelLayout.setHorizontalGroup(
            dataKendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataKendaraanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dataKendaraanPanelLayout.setVerticalGroup(
            dataKendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataKendaraanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Kendaraan", dataKendaraanPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void dataPelangganPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_dataPelangganPanelComponentShown
        showPelanggan();
    }//GEN-LAST:event_dataPelangganPanelComponentShown

    private void hapusPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPelangganButtonActionPerformed
        String query = pilihPelangganField.getText();
        try {
            Koneksi conn = new Koneksi();
            conn.query("DELETE FROM pelanggan WHERE pelanggan_id = '" + query + "'");
        } catch (Exception e){}
        namaPelangganField.setText("");
        namaPelangganField.setEnabled(false);
        alamatTextArea.setText("");
        alamatTextArea.setEnabled(false);
        cpField.setText("");
        cpField.setEnabled(false);
        simpanPelangganButton.setEnabled(false);
        hapusPelangganButton.setEnabled(false);
        batalPelangganButton.setEnabled(false);
        baruPelangganButton.setEnabled(true);
        pilihPelangganButton.setEnabled(true);
        pilihPelangganField.setText("");
        pilihPelangganField.setEnabled(true);
        refreshPelanggan();
        showPelanggan();
    }//GEN-LAST:event_hapusPelangganButtonActionPerformed

    private void cariPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariPelangganButtonActionPerformed
        refreshPelanggan();
        String query = cariPelangganField.getText();
        int baris = 0;
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM pelanggan WHERE nama LIKE '%" + query + "%'");

            while (rs.next()){
                testTable.setValueAt(rs.getString("pelanggan_id"), baris, 0);
                testTable.setValueAt(rs.getString("nama"), baris, 1);
                testTable.setValueAt(rs.getString("alamat"), baris, 2);
                testTable.setValueAt(rs.getString("cp"), baris, 3);
                baris++;
            }
        } catch (SQLException e){}
    }//GEN-LAST:event_cariPelangganButtonActionPerformed

    private void simpanPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPelangganButtonActionPerformed
        try {
            Koneksi conn = new Koneksi();
            if (pilihPelangganField.getText().equals("")){
                conn.query("INSERT INTO pelanggan (nama, alamat, cp) VALUES ('"+namaPelangganField.getText()+"','"+alamatTextArea.getText()+"','"+cpField.getText()+"')");
            } else{
                conn.query("UPDATE pelanggan SET nama='"+namaPelangganField.getText()+"', alamat='"+alamatTextArea.getText()+"', cp='"+cpField.getText()+"' WHERE pelanggan_id='"+pilihPelangganField.getText()+"'");
            }
        } catch (Exception e){}
        namaPelangganField.setText("");
        namaPelangganField.setEnabled(false);
        alamatTextArea.setText("");
        alamatTextArea.setEnabled(false);
        cpField.setText("");
        cpField.setEnabled(false);
        simpanPelangganButton.setEnabled(false);
        hapusPelangganButton.setEnabled(false);
        batalPelangganButton.setEnabled(false);
        baruPelangganButton.setEnabled(true);
        pilihPelangganButton.setEnabled(true);
        pilihPelangganField.setText("");
        pilihPelangganField.setEnabled(true);
        refreshPelanggan();
        showPelanggan();
    }//GEN-LAST:event_simpanPelangganButtonActionPerformed

    private void baruPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baruPelangganButtonActionPerformed
        namaPelangganField.setEnabled(true);
        alamatTextArea.setEnabled(true);
        cpField.setEnabled(true);
        simpanPelangganButton.setEnabled(true);
        batalPelangganButton.setEnabled(true);
        baruPelangganButton.setEnabled(false);
        pilihPelangganButton.setEnabled(false);
        pilihPelangganField.setText("");
        pilihPelangganField.setEnabled(false);
    }//GEN-LAST:event_baruPelangganButtonActionPerformed

    private void batalPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalPelangganButtonActionPerformed
        namaPelangganField.setText("");
        namaPelangganField.setEnabled(false);
        alamatTextArea.setText("");
        alamatTextArea.setEnabled(false);
        cpField.setText("");
        cpField.setEnabled(false);
        simpanPelangganButton.setEnabled(false);
        hapusPelangganButton.setEnabled(false);
        batalPelangganButton.setEnabled(false);
        baruPelangganButton.setEnabled(true);
        pilihPelangganButton.setEnabled(true);
        pilihPelangganField.setEnabled(true);
    }//GEN-LAST:event_batalPelangganButtonActionPerformed

    private void pilihPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihPelangganButtonActionPerformed
        if (cekPelanggan(pilihPelangganField.getText())){
            String id = pilihPelangganField.getText();
            ResultSet rs = null;
            try{
                Koneksi conn = new Koneksi();
                rs = conn.getData("SELECT * FROM pelanggan WHERE pelanggan_id='"+id+"'");
                
                while (rs.next()){
                    namaPelangganField.setText(rs.getString("nama"));
                    alamatTextArea.setText(rs.getString("alamat"));
                    cpField.setText(rs.getString("cp"));
                }
            } catch (SQLException e) {}
            namaPelangganField.setEnabled(true);
            alamatTextArea.setEnabled(true);
            cpField.setEnabled(true);
            simpanPelangganButton.setEnabled(true);
            hapusPelangganButton.setEnabled(true);
            batalPelangganButton.setEnabled(true);
            baruPelangganButton.setEnabled(false);
            pilihPelangganButton.setEnabled(false);
            pilihPelangganField.setEnabled(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "ID tidak ditemukan");
        }
    }//GEN-LAST:event_pilihPelangganButtonActionPerformed

    private void keluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_keluarButtonActionPerformed

    private void hapusKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusKendaraanButtonActionPerformed
        String query = pilihKendaraanField.getText();
        try {
            Koneksi conn = new Koneksi();
            conn.query("DELETE FROM kendaraan WHERE kendaraan_id = '" + query + "'");
        } catch (Exception e){}
        jenisField.setText("");
        jenisField.setEnabled(false);
        hargaField.setText("");
        hargaField.setEnabled(false);
        stokField.setText("");
        stokField.setEnabled(false);
        simpanKendaraanButton.setEnabled(false);
        hapusKendaraanButton.setEnabled(false);
        batalKendaraanButton.setEnabled(false);
        baruKendaraanButton.setEnabled(true);
        pilihKendaraanButton.setEnabled(true);
        pilihKendaraanField.setText("");
        pilihKendaraanField.setEnabled(true);
    }//GEN-LAST:event_hapusKendaraanButtonActionPerformed

    private void simpanKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanKendaraanButtonActionPerformed
        try {
            Koneksi conn = new Koneksi();
            if (pilihKendaraanField.getText().equals("")){
                conn.query("INSERT INTO kendaraan (jenis, harga, stok) VALUES ('"+jenisField.getText()+"','"+hargaField.getText()+"','"+stokField.getText()+"')");
            } else{
                conn.query("UPDATE kendaraan SET jenis='"+jenisField.getText()+"', harga='"+hargaField.getText()+"', stok='"+stokField.getText()+"' WHERE kendaraan_id='"+pilihKendaraanField.getText()+"'");
            }
        } catch (Exception e){}
        jenisField.setText("");
        jenisField.setEnabled(false);
        hargaField.setText("");
        hargaField.setEnabled(false);
        stokField.setText("");
        stokField.setEnabled(false);
        simpanKendaraanButton.setEnabled(false);
        hapusKendaraanButton.setEnabled(false);
        batalKendaraanButton.setEnabled(false);
        baruKendaraanButton.setEnabled(true);
        pilihKendaraanButton.setEnabled(true);
        pilihKendaraanField.setText("");
        pilihKendaraanField.setEnabled(true);
    }//GEN-LAST:event_simpanKendaraanButtonActionPerformed

    private void baruKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baruKendaraanButtonActionPerformed
        jenisField.setEnabled(true);
        hargaField.setEnabled(true);
        stokField.setEnabled(true);
        simpanKendaraanButton.setEnabled(true);
        batalKendaraanButton.setEnabled(true);
        baruKendaraanButton.setEnabled(false);
        pilihKendaraanButton.setEnabled(false);
        pilihKendaraanField.setText("");
        pilihKendaraanField.setEnabled(false);
    }//GEN-LAST:event_baruKendaraanButtonActionPerformed

    private void batalKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalKendaraanButtonActionPerformed
        jenisField.setText("");
        jenisField.setEnabled(false);
        hargaField.setText("");
        hargaField.setEnabled(false);
        stokField.setText("");
        stokField.setEnabled(false);
        simpanKendaraanButton.setEnabled(false);
        hapusKendaraanButton.setEnabled(false);
        batalKendaraanButton.setEnabled(false);
        baruKendaraanButton.setEnabled(true);
        pilihKendaraanButton.setEnabled(true);
        pilihKendaraanField.setEnabled(true);
    }//GEN-LAST:event_batalKendaraanButtonActionPerformed

    private void pilihKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihKendaraanButtonActionPerformed
        if (cekKendaraan(pilihKendaraanField.getText())){
            String id = pilihKendaraanField.getText();
            ResultSet rs = null;
            try{
                Koneksi conn = new Koneksi();
                rs = conn.getData("SELECT * FROM kendaraan WHERE kendaraan_id='"+id+"'");
                
                while (rs.next()){
                    jenisField.setText(rs.getString("jenis"));
                    hargaField.setText(rs.getString("harga"));
                    stokField.setText(rs.getString("stok"));
                    rs.close();
                }
            } catch (SQLException e) {}
            jenisField.setEnabled(true);
            hargaField.setEnabled(true);
            stokField.setEnabled(true);
            simpanKendaraanButton.setEnabled(true);
            hapusKendaraanButton.setEnabled(true);
            batalKendaraanButton.setEnabled(true);
            baruKendaraanButton.setEnabled(false);
            pilihKendaraanButton.setEnabled(false);
            pilihKendaraanField.setEnabled(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "ID tidak ditemukan");
        }
    }//GEN-LAST:event_pilihKendaraanButtonActionPerformed
   
    private boolean cekPelanggan(String id){
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM pelanggan WHERE pelanggan_id='"+id+"'");
            if (rs.next()){
                rs.close();
                return true;
            }
        } catch (SQLException e) {}
        return false;
    }

    private boolean cekKendaraan(String id){
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM kendaraan WHERE kendaraan_id='"+id+"'");
            if (rs.next()){
                rs.close();
                return true;
            }
        } catch (SQLException e) {}
        return false;
    }
    
    private void refreshPelanggan(){
        for (int i=0; i<10; i++){
            for (int j=0; j<4; j++){
                testTable.setValueAt("", i, j);
            }
        }
    }
    
    private void showPelanggan(){
        int baris = 0;
        try {
            Koneksi conn = new Koneksi();
            ResultSet rs = null;
            rs = conn.getData("SELECT * FROM pelanggan");

            while (rs.next()){
                testTable.setValueAt(rs.getString("pelanggan_id"), baris, 0);
                testTable.setValueAt(rs.getString("nama"), baris, 1);
                testTable.setValueAt(rs.getString("alamat"), baris, 2);
                testTable.setValueAt(rs.getString("cp"), baris, 3);
                baris++;
            }
        } catch (SQLException e){}
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rental().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JTextArea alamatTextArea;
    private javax.swing.JButton baruKendaraanButton;
    private javax.swing.JButton baruPelangganButton;
    private javax.swing.JButton batalKendaraanButton;
    private javax.swing.JButton batalPelangganButton;
    private javax.swing.JButton cariPelangganButton;
    private javax.swing.JTextField cariPelangganField;
    private javax.swing.JTextField cpField;
    private javax.swing.JLabel cpLabel;
    private javax.swing.JPanel dataKendaraanPanel;
    private javax.swing.JPanel dataPelangganPanel;
    private javax.swing.JButton hapusKendaraanButton;
    private javax.swing.JButton hapusPelangganButton;
    private javax.swing.JTextField hargaField;
    private javax.swing.JLabel hargaLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jenisField;
    private javax.swing.JLabel jenisLabel;
    private javax.swing.JButton keluarButton;
    private javax.swing.JTextField namaPelangganField;
    private javax.swing.JLabel namaPelangganLabel;
    private javax.swing.JButton pilihKendaraanButton;
    private javax.swing.JTextField pilihKendaraanField;
    private javax.swing.JButton pilihPelangganButton;
    private javax.swing.JTextField pilihPelangganField;
    private javax.swing.JButton simpanKendaraanButton;
    private javax.swing.JButton simpanPelangganButton;
    private javax.swing.JTextField stokField;
    private javax.swing.JLabel stokLabel;
    private javax.swing.JTable testTable;
    // End of variables declaration//GEN-END:variables
}
